<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CK.AppIdentity" Version="0.14.0--ci.9" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CK.Monitoring.Metrics\CK.Monitoring.Metrics.csproj" />
  </ItemGroup>
</Project>